<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="nayans-MacBook-Air.local" failures="1" tests="1" name="test(failed)" time="0.042" errors="0" timestamp="11 Apr 2019 13:07:22 GMT">
  <testcase classname="TestBase.TestBase" name="@AfterTest quitBrowser" time="0.001">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at TestBase.TestBase.quitBrowser(TestBase.java:84)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- @AfterTest quitBrowser -->
  <testcase classname="TestBase.loginCRM" name="checkValue" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [True] but found [False]">
      <![CDATA[java.lang.AssertionError: expected [True] but found [False]
at TestBase.loginCRM.checkValue(loginCRM.java:37)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkValue -->
  <testcase classname="TestBase.loginCRM" name="logincrm_function" time="0.0">
    <ignored/>
  </testcase> <!-- logincrm_function -->
</testsuite> <!-- test(failed) -->
